function [fitresult, gof] = createFit_V_w_i(w, C, V)
%CREATEFIT(W,C,V)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : w
%      Y Input : C
%      Z Output: V
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Sep-2018 21:49:46


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( w, C, V );

% Set up fittype and options.
ft = fittype( 'a*x+b*y', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.880199247960464 0.90427446328796];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'V vs. w, C', 'Location', 'NorthEast' );
% Label axes
xlabel w
ylabel C
zlabel V
grid on
view( -5.1, 11.6 );


