function [fitresult, gof] = createFit_Q_w_i(w, C, Torque)
%CREATEFIT(W,C,TORQUE)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : w
%      Y Input : C
%      Z Output: Torque
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Sep-2018 21:25:06


%% Fit: 'untitled fit 2'.
[xData, yData, zData] = prepareSurfaceData( w, C, Torque );

% Set up fittype and options.
ft = fittype( '-a*x+b*y-c*y*y', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0];
opts.StartPoint = [0.96547576709165 0.686518049744488 0.55498228428808];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 2', 'Torque vs. w, C', 'Location', 'NorthEast' );
% Label axes
xlabel('Rotational speed (rpm)');
ylabel('Current (A)');
zlabel('Torque (Nm)');
grid on
view( -41.1, -2.8 );


