function [fitresult, gof] = createFit_power(Thrust_avg, Command_avg)
%CREATEFIT(THRUST_AVG,COMMAND_AVG)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Thrust_avg
%      Y Output: Command_avg
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Jul-2018 15:37:34


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Thrust_avg, Command_avg );

% Set up fittype and options.
ft = fittype( 'power2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [21.3955464205589 1.25703940649607 -42.0810530754652];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Command_avg vs. Thrust_avg', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel Thrust_avg
ylabel Command_avg
grid on


